version: '3.2'
services:
  php:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 80:80
    links:
      - mysql:db
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: docker
      MYSQL_ROOT_PASSWORD: password
  composer:
    restart: 'no'
    image: composer/composer:php7
    command: ["install","--ignore-platform-reqs","--no-scripts"]
    volumes:
      - .:/app